# Generated by Django 5.2.3 on 2025-09-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaG', '0004_product_supplier_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('alimentos', 'Alimentos'), ('utiles', 'Útiles escolares'), ('peluqueria', 'Peluquería')], max_length=50, null=True),
        ),
    ]
