# Generated by Django 5.2.3 on 2025-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaG', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
