# Generated by Django 5.2.3 on 2025-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaG', '0006_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('alimentos', 'Alimentos'), ('utiles', 'Útiles escolares'), ('peluqueria', 'Peluquería'), ('cosmetica', 'Cosmética'), ('limpieza', 'Limpieza')], max_length=50, null=True),
        ),
    ]
