# Generated by Django 5.2.3 on 2025-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontaG', '0008_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(related_name='suppliers', to='kontaG.product'),
        ),
    ]
