# Generated by Django 5.2.3 on 2025-10-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_suggestion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_assigned_suggestions',
            field=models.CharField(default='Blank', max_length=5000),
        ),
    ]
