# Generated by Django 5.2.3 on 2025-10-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_price_suggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_assigned_suggestions',
            field=models.CharField(blank=True, default='Blank', max_length=5000, null=True),
        ),
    ]
