# Generated by Django 5.2.5 on 2025-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="min_stock",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
